SELECT TTCL.CNTR_OPER_CODE,
TTCL.CNTR_NUM AS CNTR_AN,
TTCL.CNTR_TYPE AS CONTAINER_TYPE_CODE,
decode(TTCL.CNTR_LADEN_STATUS,'E','4','F','5','4')AS LADEN_INDICATOR_AN, 
nvl(decode(TTCL.CNTR_LADEN_STATUS,'E',(SELECT T.BOOKING_AN FROM TMS_CNTR_GRP1 C, TMS_TRML_DOC_REF T WHERE C.terminal_doc_ref_an= t.terminal_doc_ref_an(+) and c.CNTR_AN=TTCL.CNTR_NUM)),'NOBOOKING')AS BOOKING_NO_AN,
TO_CHAR(TTCL.CNTR_ARRIVE_TM,'YYYYMMDDHH24MI') AS ACTIVITY_TM,
decode(TTCL.WEIGHT_UOM,'MT',TTCL.CNTR_GROSS_WGT*1000,TTCL.CNTR_GROSS_WGT)AS GWEIGHT,
(SELECT C.AREA_C FROM TMS_CNTR_GRP1 C WHERE c.CNTR_AN=TTCL.CNTR_NUM) AS AREA_C 
FROM TMS_OWNER.TMV_CNTR_CYCLE_LIST TTCL  
WHERE TTCL.CNTR_ARRIVE_TM  between to_date(':START_DATE','DD-MON-YYYY HH24:MI') AND to_date(':END_DATE','DD-MON-YYYY HH24:MI') 
AND TTCL.SHIPPING_STATUS_CODE LIKE 'ST'
AND TTCL.CNTR_OPER_CODE = 'ONE'
AND (SELECT C.AREA_C FROM TMS_CNTR_GRP1 C WHERE c.CNTR_AN=TTCL.CNTR_NUM) LIKE :BERTH 